service: slowquery-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2023
  region: ap-northeast-1
  logRetentionInDays: 1
  timeout: 60
  environment:
    KEY_SLACK_INCOMING_WEBHOOK_URL: '一旦仮の値'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ssm:GetParameter'
        - 'ssm:GetParameters'
      Resource: '*'
custom:
  go:
    cmd: GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"
    supportedRuntimes: [ "provided.al2023" ]
    buildProvidedRuntimeAsBootstrap: true

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  slowquery:
    name: slowquery
    handler: bin/trigger
    events:
      - cloudwatchLog: /aws/rds/cluster/test-cluster-for-test/error
